export const CONTRACTOR_ADD_REQUEST = "CONTRACTOR_ADD_REQUEST";
export const CONTRACTOR_ADD_SUCCESS = "CONTRACTOR_ADD_SUCCESS";
export const CONTRACTOR_ADD_FAIL = "CONTRACTOR_ADD_FAIL";
export const CONTRACTOR_ADD_RESET = "CONTRACTOR_ADD_RESET";

export const CONTRACTOR_FETCH_REQUEST = "CONTRACTOR_FETCH_REQUEST";
export const CONTRACTOR_FETCH_SUCCESS = "CONTRACTOR_FETCH_SUCCESS";
export const CONTRACTOR_FETCH_FAIL = "CONTRACTOR_FETCH_FAIL";
export const CONTRACTOR_FETCH_RESET = "CONTRACTOR_FETCH_RESET";

export const CONTRACTOR_UPDATE_REQUEST = "CONTRACTOR_UPDATE_REQUEST";
export const CONTRACTOR_UPDATE_SUCCESS = "CONTRACTOR_UPDATE_SUCCESS";
export const CONTRACTOR_UPDATE_FAIL = "CONTRACTOR_UPDATE_FAIL";
export const CONTRACTOR_UPDATE_RESET = "CONTRACTOR_UPDATE_RESET";

export const CONTRACTOR_ENABLE_REQUEST = "CONTRACTOR_ENABLE_REQUEST";
export const CONTRACTOR_ENABLE_SUCCESS = "CONTRACTOR_ENABLE_SUCCESS";
export const CONTRACTOR_ENABLE_FAIL = "CONTRACTOR_ENABLE_FAIL";
export const CONTRACTOR_ENABLE_RESET = "CONTRACTOR_ENABLE_RESET";

export const CONTRACTOR_DISABLE_REQUEST = "CONTRACTOR_DISABLE_REQUEST";
export const CONTRACTOR_DISABLE_SUCCESS = "CONTRACTOR_DISABLE_SUCCESS";
export const CONTRACTOR_DISABLE_FAIL = "CONTRACTOR_DISABLE_FAIL";
export const CONTRACTOR_DISABLE_RESET = "CONTRACTOR_DISABLE_RESET";
