export const MESSAGE_FETCH_REQUEST = "MESSAGE_FETCH_REQUEST";
export const MESSAGE_FETCH_SUCCESS = "MESSAGE_FETCH_SUCCESS";
export const MESSAGE_FETCH_FAIL = "MESSAGE_FETCH_FAIL";
export const MESSAGE_FETCH_RESET = "MESSAGE_FETCH_RESET";

export const MESSAGE_UPDATE_REQUEST = "MESSAGE_UPDATE_REQUEST";
export const MESSAGE_UPDATE_SUCCESS = "MESSAGE_UPDATE_SUCCESS";
export const MESSAGE_UPDATE_FAIL = "MESSAGE_UPDATE_FAIL";
export const MESSAGE_UPDATE_RESET = "MESSAGE_UPDATE_RESET";
