export const FILE_UPLOADING = "FILE_UPLOADING";
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const UPLOAD_DONE = "UPLOAD_DONE";
export const UPLOAD_FAIL = "UPLOAD_FAIL";
export const UPLOAD_RESET = "UPLOAD_RESET";

export const ABOUT_FETCH_REQUEST = "ABOUT_FETCH_REQUEST";
export const ABOUT_FETCH_SUCCESS = "ABOUT_FETCH_SUCCESS";
export const ABOUT_FETCH_FAIL = "ABOUT_FETCH_FAIL";
export const ABOUT_FETCH_RESET = "ABOUT_FETCH_RESET";

export const ABOUT_UPDATE_REQUEST = "ABOUT_UPDATE_REQUEST";
export const ABOUT_UPDATE_SUCCESS = "ABOUT_UPDATE_SUCCESS";
export const ABOUT_UPDATE_FAIL = "ABOUT_UPDATE_FAIL";
export const ABOUT_UPDATE_RESET = "ABOUT_UPDATE_RESET";
